# Data Exploration Code

In [ ]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Load the data
df = pd.read_csv('../data/hmeq.csv')

In [14]:
# Show databse shape and taget variable distribution
print("="*60)
print("Dataset Shape")
print("="*60)
print(f"rows: {df.shape[0]}")
print(f"cols: {df.shape[1]}")

print("\n")
print("="*60)
print("Target Variable Distribution")
print("="*60)
print(df["BAD"].value_counts())

============================================================
Dataset Shape
============================================================
rows: 5960
cols: 13


============================================================
Target Variable Distribution
============================================================
BAD
0    4771
1    1189
Name: count, dtype: int64

In [ ]:
# Evaualte missing data
print("="*60)
print("Missing Values:")
print("="*60)
missing = df.isnull().sum()
missing_percentage = (missing / len(df)) * 100
missing_df = pd.DataFrame({
    "Missing_count" : missing,
    "Missing_percentage" : missing_percentage   
}).sort_values("Missing_percentage", ascending=False)
missing_df

# debt-to-income has a missing % of 21, highest cat

============================================================
Missing Values:
============================================================

         Missing_count  Missing_percentage
DEBTINC           1267           21.258389
DEROG              708           11.879195
DELINQ             580            9.731544
MORTDUE            518            8.691275
YOJ                515            8.640940
NINQ               510            8.557047
CLAGE              308            5.167785
JOB                279            4.681208
REASON             252            4.228188
CLNO               222            3.724832
VALUE              112            1.879195
LOAN                 0            0.000000
BAD                  0            0.000000

In [21]:
df.head()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,1100,25860.0,39025.0,HomeImp,Other,10.5,0.0,0.0,94.366667,1.0,9.0,NaN
1,1,1300,70053.0,68400.0,HomeImp,Other,7.0,0.0,2.0,121.833333,0.0,14.0,NaN
2,1,1500,13500.0,16700.0,HomeImp,Other,4.0,0.0,0.0,149.466667,1.0,10.0,NaN
3,1,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,1700,97800.0,112000.0,HomeImp,Office,3.0,0.0,0.0,93.333333,0.0,14.0,NaN